/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package turbo_flyer_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Arquivo_Ou_Pasta;
import br.com.jmary.utilidades.Exportando;
import turbo_flyer.Gerenciador_Email_02_Cadastrar_Visualizar;

/**
 *
 * @author ana
 */
public class Gerenciador_Email_Submenu_01 extends javax.swing.JPanel {

    Home Home;
        
    public Gerenciador_Email_Submenu_01( Home Home2 ) {
        Home = Home2;
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btExercicios5 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator11.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator11);

        btExercicios5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/foguete.png"))); // NOI18N
        btExercicios5.setText("Turbo Flyer");
        btExercicios5.setFocusable(false);
        btExercicios5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExercicios5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios5MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios5);

        jSeparator8.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    Exportando Exportando;
    private void btExercicios5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios5MousePressed
        /*
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.AddTabsAoHome("EmailZap Índice", "livroTp.gif", new Gerenciador_Email_01_Indice(Home) ); 

        } catch( Exception e ){ } } }.start();
        */
        new Thread() {   @Override public void run() { try { 
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            //Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome("Turbo Flyer", "livroTp.gif", 
                    new Gerenciador_Email_02_Cadastrar_Visualizar(Home, Home.tabHome, "Cadastrando...") );
            
            //Tabela Tabela = new Tabela("Cleilson-Henrique");
            //Home.ControleTabs.AddTabsAoHome("Cadastrar/Visualizar Controle de Acesso", "livroTp.gif", Tabela );

            
            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } } }.start();
    }//GEN-LAST:event_btExercicios5MousePressed
    
    int count = 0;
    private void cd(){
        
        Arquivo_Ou_Pasta.criarPasta(System.getProperty("user.dir"), "Diego");
        
        for( int v = 1; v<=50; v++ ){
            count++;
            
            String c = "=IF( $B$"+x+"=1; 'FICHAS TECNICAS'!D"+2+";\n" +
"    IF( $B$"+x+"=2; 'FICHAS TECNICAS'!D"+35+";\n" +
"\n" +
"        IF( $B$"+x+"=3; 'FICHAS TECNICAS'!D"+68+";\n" +
"\n" +
"            IF( $B$"+x+"=4; 'FICHAS TECNICAS'!D"+101+";\n" +
"\n" +
"                IF( $B$"+x+"=5; 'FICHAS TECNICAS'!D"+134+";\n" +
"\n" +
"                   IF( $B$"+x+"=6; 'FICHAS TECNICAS'!D"+167+";\n" +
"\n" +
"                       IF( $B$"+x+"=7; 'FICHAS TECNICAS'!D"+200+";\n" +
"\n" +
"                            IF( $B$"+x+"=8; 'FICHAS TECNICAS'!D"+233+";\n" +
"\n" +
"                                IF( $B$"+x+"=9; 'FICHAS TECNICAS'!D"+266+";\n" +
"\n" +
"                                   IF( $B$"+x+"=10; 'FICHAS TECNICAS'!D"+299+";\n" +
"\n" +
"                                        IF( $B$"+x+"=11; 'FICHAS TECNICAS'!D"+332+";\n" +
"\n" +
"                                            IF( $B$"+x+"=12; 'FICHAS TECNICAS'!D"+365+";\n" +
"\n" +
"                                                IF( $B$"+x+"=13; 'FICHAS TECNICAS'!D"+398+";\n" +
"\n" +
"                                                    IF( $B$"+x+"=14; 'FICHAS TECNICAS'!D"+431+";\n" +
"\n" +
"IF( $B$"+x+"=15; 'FICHAS TECNICAS'!D"+464+";\n" +
"\n" +
"IF( $B$"+x+"=16; 'FICHAS TECNICAS'!D"+497+";\n" +
"\n" +
"IF( $B$"+x+"=17; 'FICHAS TECNICAS'!D"+530+";\n" +
"\n" +
"IF( $B$"+x+"=18; 'FICHAS TECNICAS'!D"+563+";\n" +
"IF( $B$"+x+"=19; 'FICHAS TECNICAS'!D"+596+";\n" +
"\n" +
"IF( $B$"+x+"=20; 'FICHAS TECNICAS'!D"+629+";\n" +
"\n" +
"IF( $B$"+x+"=21; 'FICHAS TECNICAS'!D"+662+";\n" +
"\n" +
"IF( $B$"+x+"=22; 'FICHAS TECNICAS'!D"+695+";\n" +
"\n" +
"IF( $B$"+x+"=23; 'FICHAS TECNICAS'!D"+728+";\n" +
"\n" +
"IF( $B$"+x+"=24; 'FICHAS TECNICAS'!D"+761+";\n" +
"\n" +
"IF( $B$"+x+"=25; 'FICHAS TECNICAS'!D"+794+";\n" +
"\n" +
"IF( $B$"+x+"=26; 'FICHAS TECNICAS'!D"+827+";\n" +
"\n" +
"IF( $B$"+x+"=27; 'FICHAS TECNICAS'!D"+860+";\n" +
"\n" +
"IF( $B$"+x+"=28; 'FICHAS TECNICAS'!D"+893+";\n" +
"\n" +
"IF( $B$"+x+"=29; 'FICHAS TECNICAS'!D"+926+";\n" +
"\n" +
"IF( $B$"+x+"=30; 'FICHAS TECNICAS'!D"+959+";\n" +
"\n" +
"IF( $B$"+x+"=31; 'FICHAS TECNICAS'!D"+992+";\n" +
"\n" +
"IF( $B$"+x+"=32; 'FICHAS TECNICAS'!D"+1025+";\n" +
"\n" +
"IF( $B$"+x+"=33; 'FICHAS TECNICAS'!D"+1058+";\n" +
"\n" +
"IF( $B$"+x+"=34; 'FICHAS TECNICAS'!D"+1091+";\n" +
"\n" +
"IF( $B$"+x+"=35; 'FICHAS TECNICAS'!D"+1124+";\n" +
"\n" +
"IF( $B$"+x+"=36; 'FICHAS TECNICAS'!D"+1157+";\n" +
"\n" +
"IF( $B$"+x+"=37; 'FICHAS TECNICAS'!D"+1190+";\n" +
"\n" +
"IF( $B$"+x+"=38; 'FICHAS TECNICAS'!D"+1223+";\n" +
"\n" +
"IF( $B$"+x+"=39; 'FICHAS TECNICAS'!D"+1256+";\n" +
"\n" +
"IF( $B$"+x+"=40; 'FICHAS TECNICAS'!D"+1289+";\n" +
"\n" +
"IF( $B$"+x+"=41; 'FICHAS TECNICAS'!D"+1322+";\n" +
"\n" +
"IF( $B$"+x+"=42; 'FICHAS TECNICAS'!D"+1355+";\n" +
"\n" +
"IF( $B$"+x+"=43; 'FICHAS TECNICAS'!D"+1388+";\n" +
"\n" +
"IF( $B$"+x+"=44; 'FICHAS TECNICAS'!D"+1421+";\n" +
"\n" +
"IF( $B$"+x+"=45; 'FICHAS TECNICAS'!D"+1454+";\n" +
"\n" +
"IF( $B$"+x+"=46; 'FICHAS TECNICAS'!D"+1487+";\n" +
"\n" +
"IF( $B$"+x+"=47; 'FICHAS TECNICAS'!D"+1520+";\n" +
"\n" +
"IF( $B$"+x+"=48; 'FICHAS TECNICAS'!D"+1553+";\n" +
"\n" +
"IF( $B$"+x+"=49; 'FICHAS TECNICAS'!D"+1586+";\n" +
"\n" +
"IF( $B$"+x+"=50; 'FICHAS TECNICAS'!D"+1619+";\n" +
"\n" +
"IF( $B$"+x+"=51; 'FICHAS TECNICAS'!D"+1619+"; \"\" )\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
")\n" +
"                                                    )\n" +
"                                                )\n" +
"                                            )\n" +
"                                        )\n" +
"                                    )\n" +
"                                )\n" +
"                            )\n" +
"                        )\n" +
"                    )\n" +
"                )\n" +
"            )\n" +
"        )\n" +
"    )\n" +
"\n" +
")";
            
            String arquivo = System.getProperty("user.dir") + "\\" + "Diego" + "\\" + count + ".txt";
            
            Arquivo_Ou_Pasta.criar_Arquivo_Iso( arquivo, c);
            
            System.out.println(c);
            x = x + 9;
            y = y + 33; 
        }
    }
    
    private void btExercicios5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios5MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_btExercicios5MouseEntered

    int x = 2;
    int y = 2;
    
    String b = "=IF( $B$"+x+"=1; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$11:$S$18;3;0);\n" +
"\n" +
"    IF( $B$"+x+"=2; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$44:$S$51;3;0);\n" +
"\n" +
"        IF( $B$"+x+"=3; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$77:$S$84;3;0);\n" +
"\n" +
"            IF( $B$"+x+"=4; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$110:$S$117;3;0);\n" +
"\n" +
"                IF( $B$"+x+"=5; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$143:$S$150;3;0);\n" +
"\n" +
"                    IF( $B$"+x+"=6; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$176:$S$183;3;0);\n" +
"\n" +
"                        IF( $B$"+x+"=7; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$209:$S$216;3;0);\n" +
"\n" +
"                            IF( $B$"+x+"=8; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$242:$S$249;3;0);\n" +
"\n" +
"                                IF( $B$"+x+"=9; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$274:$S$282;3;0);\n" +
"\n" +
"                                    IF( $B$"+x+"=10; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$308:$S$315;3;0);\n" +
"\n" +
"                                        IF( $B$"+x+"=11; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$341:$S$348;3;0);\n" +
"\n" +
"                                            IF( $B$"+x+"=12; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$374:$S$381;3;0);\n" +
"\n" +
"                                                IF( $B$"+x+"=13; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$407:$S$414;3;0);\n" +
"\n" +
"                                                    IF( $B$"+x+"=14; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$440:$S$447;3;0);\n" +
"\n" +
"                                                        IF( $B$"+x+"=15; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$473:$S$480;3;0);\n" +
"\n" +
"                                                            IF( $B$"+x+"=16; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$506:$S$513;3;0);\n" +
"\n" +
"                                                                IF( $B$"+x+"=17; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$539:$S$546;3;0);\n" +
"\n" +
"                                                                    IF( $B$"+x+"=18; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$572:$S$579;3;0);\n" +
"\n" +
"                                                                        IF( $B$"+x+"=19; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$605:$S$612;3;0);\n" +
"\n" +
"                                                                            IF( $B$"+x+"=20; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$638:$S$645;3;0);\n" +
"\n" +
"                                                                                IF( $B$"+x+"=21; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$671:$S$678;3;0);\n" +
"\n" +
"                                                                                    IF( $B$"+x+"=22; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$704:$S$711;3;0);\n" +
"\n" +
"                                                                                        IF( $B$"+x+"=23; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$737:$S$744;3;0);\n" +
"\n" +
"                                                                                            IF( $B$"+x+"=24; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$770:$S$777;3;0);\n" +
"\n" +
"                                                                                                IF( $B$"+x+"=25; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$803:$S$810;3;0);\n" +
"\n" +
"                                                                                                    IF( $B$"+x+"=26; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$836:$S$843;3;0);\n" +
"\n" +
"                                                                                                        IF( $B$"+x+"=27; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$869:$S$876;3;0);\n" +
"\n" +
"                                                                                                            IF( $B$"+x+"=28; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$902:$S$909;3;0);\n" +
"\n" +
"                                                                                                                IF( $B$"+x+"=29; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$935:$S$942;3;0);\n" +
"\n" +
"IF( $B$"+x+"=30; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$968:$S$975;3;0);\n" +
"\n" +
"IF( $B$"+x+"=31; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1001:$S$1008;3;0);\n" +
"\n" +
"IF( $B$"+x+"=32; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1034:$S$1041;3;0);\n" +
"\n" +
"IF( $B$"+x+"=33; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1067:$S$1074;3;0);\n" +
"\n" +
"IF( $B$"+x+"=34; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1100:$S$1107;3;0);\n" +
"\n" +
"IF( $B$"+x+"=35; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1133:$S$1140;3;0);\n" +
"\n" +
"IF( $B$"+x+"=36; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1166:$S$1173;3;0);\n" +
"\n" +
"IF( $B$"+x+"=37; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1199:$S$1206;3;0);\n" +
"\n" +
"IF( $B$"+x+"=38; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1232:$S$1239;3;0);\n" +
"\n" +
"IF( $B$"+x+"=39; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1265:$S$1272;3;0);\n" +
"\n" +
"IF( $B$"+x+"=40; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1298:$S$1305;3;0);\n" +
"\n" +
"IF( $B$"+x+"=41; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1331:$S$1338;3;0);\n" +
"\n" +
"IF( $B$"+x+"=42; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1364:$S$1371;3;0);\n" +
"\n" +
"IF( $B$"+x+"=43; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1397:$S$1404;3;0);\n" +
"\n" +
"IF( $B$"+x+"=44; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1430:$S$1437;3;0);\n" +
"\n" +
"IF( $B$"+x+"=45; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1463:$S$1470;3;0);\n" +
"\n" +
"IF( $B$"+x+"=46; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1496:$S$1503;3;0);\n" +
"\n" +
"IF( $B$"+x+"=47; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1529:$S$1536;3;0);\n" +
"\n" +
"IF( $B$"+x+"=48; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1562:$S$1569;3;0);\n" +
"\n" +
"IF( $B$"+x+"=49; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1595:$S$16022;3;0);\n" +
"\n" +
"IF( $B$"+x+"=50; VLOOKUP(B"+y+";'FICHAS TECNICAS'!$B$1628:$S$1635;3;0); \"\" )\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
")\n" +
"\n" +
"                                                                                                                )\n" +
"\n" +
"                                                                                                            )\n" +
"\n" +
"                                                                                                        )\n" +
"\n" +
"                                                                                                    )\n" +
"\n" +
"                                                                                                )\n" +
"\n" +
"                                                                                            )\n" +
"\n" +
"                                                                                        )\n" +
"\n" +
"                                                                                    )\n" +
"\n" +
"                                                                                )\n" +
"\n" +
"                                                                            )\n" +
"\n" +
"                                                                         )\n" +
"\n" +
"                                                                    )\n" +
"\n" +
"                                                                )\n" +
"\n" +
"                                                            )\n" +
"\n" +
"                                                        )\n" +
"                                                    )\n" +
"                                                )\n" +
"                                            )\n" +
"                                        )\n" +
"                                    )\n" +
"                                )\n" +
"                            )\n" +
"                        )\n" +
"                    )\n" +
"                )\n" +
"            )\n" +
"        )\n" +
"    )\n" +
"\n" +
")";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExercicios5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
